packages:
  - apps/*
  - packages/*
  - packages/bundles/*
  - tools/*
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  koffi: true
  node-pty: true
  protobufjs: false
  esbuild: true
  electron-winstaller: true
